'use strict';

var Promise = require('bluebird');
var assert = require('assert');

/**
 * Generates values as given by the iterator
 * @param {array} values
 * @param {int} [idxFrom]
 * @param {int} [idxBefore]
 * @returns {Function}
 */
module.exports.generator = function generator(values, idxFrom, idxBefore) {
    var i = 0;
    return function () {
        var result = undefined;
        while (idxFrom !== undefined && i < values.length && values[i] < idxFrom) {
            i++;
        }
        if (i < values.length && (idxBefore === undefined || values[i] < idxBefore)) {
            result = {idx: values[i++]};
        }
        return Promise.resolve(result);
    }
};


/**
 * Checks that values generated by the iterator match expected values
 * Adapted from promistreamus tests
 */
module.exports.assertInOrder = function assertInOrder(msg, expectedValues, iterator, deep) {
    var pos = 0;
    var processor = function () {
        return iterator().then(function (value) {
            if (value === undefined) {
                assert.equal(pos, expectedValues.length, 'finished early');
                return undefined;
            }
            assert(pos < expectedValues.length, 'too many values');
            var expectedVal = expectedValues[pos++];
            if (deep)
                assert.deepEqual(value, expectedVal, 'unexpected value');
            else
                assert.equal(value.idx, expectedVal, 'unexpected value');

            return processor();
        });
    };
    return processor().catch(function (err) {
        err.message = msg + ': ' + err.message;
        assert.fail(err);
    });
};
